### ISSUE TITLE
MPEG-4 video hang

### ISSUE THREAD

**Issue by bkrepo** [OtherCrashOverride/c2play#20] opened 2016-12-21 01:47 UTC
```
odroid@odroid64:~/c2play$ ./c2play ../Toy\ Story\ 3\ -\ Trailer\ 3\ 6450_D1.mp4 
added device: /dev/input/event4
added device: /dev/input/event3
added device: /dev/input/mouse0
added device: /dev/input/event2
added device: /dev/input/event1
added device: /dev/input/event0
added device: /dev/input/mice
Device: /dev/input/event4
        bustype=0, vendor=0, product=0, version=0
        name=lircd
InputDevice entering running state.
Device: /dev/input/event3
        bustype=0, vendor=0, product=0, version=0
        name=MCE IR Keyboard/Mouse (meson-ir)
InputDevice entering running state.
Device: /dev/input/mouse0
EVIOCGBIT failed.
Device: /dev/input/event2
        bustype=25, vendor=0, product=0, version=0
        name=meson-ir
InputDevice entering running state.
Device: /dev/input/event1
        bustype=25, vendor=5812, product=1793, version=1
        name=vt-input
InputDevice entering running state.
Device: /dev/input/event0
        bustype=16, vendor=7054, product=3308, version=1
        name=cec_input
InputDevice entering running state.
Device: /dev/input/mice
EVIOCGBIT failed.
Using input device: lircd
Using input device: MCE IR Keyboard/Mouse (meson-ir)
Using input device: meson-ir
Using input device: vt-input
Using input device: cec_input
Could not open /dev/tty0
EGL: major=1, minor=4
EGL: Vendor=ARM
EGL: Version=1.4 Linux-r6p1-01rel0
EGL: ClientAPIs=OpenGL_ES
EGL: Extensions=EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_gl_texture_2D_image EGL_ 
EGL: ClientExtensions=EGL_EXT_client_extensions EGL_EXT_platform_base 

Source Metadata:
        key=major_brand, value=isom
        key=minor_version, value=512
        key=compatible_brands, value=mp41
        key=creation_time, value=1970-01-01 00:00:00
        key=encoder, value=PotEncoder
Duration: 149.800000
Streams (count=2):
stream #0 - VIDEO/MPEG4
        w=800 h=480 fps=30.000000(30/1) SAR=(0/1) 
stream #1 - AUDIO/AAC
AmlCodec: amstream version : 2.0
Element (AudioCodec) Flush exited.
Element (AudioSink) Flush exited.
AmlVideoSinkElement: calling base.
Element (VideoSink) Flush exited.
AmlVideoSinkElement: Flush exited.
Element (Source) Flush exited.
Element (VideoSink) ChangeState oldState=0 newState=1.
Element (AudioCodec) ChangeState oldState=0 newState=1.
Element (AudioSink) ChangeState oldState=0 newState=1.
Element (Source) ChangeState oldState=0 newState=1.
AmlVideoSink: ExtraData size=46
AmlVideoSink - VIDEO/MPEG4
        w=800 h=480 fps=30.000000 am_sysinfo.rate=3201 
AmlVideoSinkElement: got marker buffer Marker=2
Header (pkt.size=a916):
00 00 01 b3 00 10 07 00 00 01 b6 10 60 4d 20 5f 
isAnnexB=0
AudioCodecElement: outInfo->SampleRate=44100, outInfo->Channels=2
AlsaAudioSinkElement: isFirstData changed.
SetupAlsa: frameSize=1024
AmlVideoSink: Adjust PTS - pts=0.115033 vpts=0.033333 drift=-0.081700 (-2.451000 frames)
AmlVideoSink: Adjust PTS - pts=0.115644 vpts=0.033333 drift=-0.082311 (-2.469333 frames)
AmlVideoSink: Adjust PTS - pts=0.116278 vpts=0.033333 drift=-0.082944 (-2.488333 frames)
AmlVideoSink: Adjust PTS - pts=0.116911 vpts=0.033333 drift=-0.083578 (-2.507333 frames)
AmlVideoSink: Adjust PTS - pts=0.199456 vpts=0.033333 drift=-0.166122 (-4.983667 frames)
AmlVideoSink: Adjust PTS - pts=0.200089 vpts=0.033333 drift=-0.166756 (-5.002667 frames)
AmlVideoSink: Adjust PTS - pts=0.201222 vpts=0.033333 drift=-0.167889 (-5.036667 frames)
AmlVideoSink: Adjust PTS - pts=0.202311 vpts=0.033333 drift=-0.168978 (-5.069333 frames)
AmlVideoSink: Adjust PTS - pts=0.294489 vpts=0.033333 drift=-0.261156 (-7.834667 frames)
AmlVideoSink: Adjust PTS - pts=0.294933 vpts=0.033333 drift=-0.261600 (-7.848000 frames)
AmlVideoSink: Adjust PTS - pts=0.381600 vpts=0.033333 drift=-0.348267 (-10.448000 frames)
AmlVideoSink: Adjust PTS - pts=0.381922 vpts=0.033333 drift=-0.348589 (-10.457667 frames)
AmlVideoSink: Adjust PTS - pts=0.499967 vpts=0.033333 drift=-0.466633 (-13.999000 frames)
AmlVideoSink: Adjust PTS - pts=0.500289 vpts=0.033333 drift=-0.466956 (-14.008667 frames)
AmlVideoSink: Adjust PTS - pts=0.500811 vpts=0.033333 drift=-0.467478 (-14.024333 frames)
AmlVideoSink: Adjust PTS - pts=0.610067 vpts=0.033333 drift=-0.576733 (-17.302000 frames)
AmlVideoSink: Adjust PTS - pts=0.610400 vpts=0.033333 drift=-0.577067 (-17.312000 frames)
AmlVideoSink: Adjust PTS - pts=0.610789 vpts=0.033333 drift=-0.577456 (-17.323667 frames)
AmlVideoSink: Adjust PTS - pts=0.731356 vpts=0.033333 drift=-0.698022 (-20.940667 frames)
AmlVideoSink: Adjust PTS - pts=0.731744 vpts=0.033333 drift=-0.698411 (-20.952333 frames)
AmlVideoSink: Adjust PTS - pts=0.732056 vpts=0.033333 drift=-0.698722 (-20.961667 frames)
AmlVideoSink: Adjust PTS - pts=0.732333 vpts=0.033333 drift=-0.699000 (-20.970000 frames)
AmlVideoSink: Adjust PTS - pts=0.732467 vpts=0.033333 drift=-0.699133 (-20.974000 frames)
AmlVideoSink: Adjust PTS - pts=0.822833 vpts=0.033333 drift=-0.789500 (-23.685000 frames)
AmlVideoSink: Adjust PTS - pts=0.823211 vpts=0.033333 drift=-0.789878 (-23.696333 frames)
AmlVideoSink: Adjust PTS - pts=0.823422 vpts=0.033333 drift=-0.790089 (-23.702667 frames)
AmlVideoSink: Adjust PTS - pts=0.823578 vpts=0.033333 drift=-0.790244 (-23.707333 frames)
AmlVideoSink: Adjust PTS - pts=0.914600 vpts=0.033333 drift=-0.881267 (-26.438000 frames)
AmlVideoSink: Adjust PTS - pts=0.914822 vpts=0.033333 drift=-0.881489 (-26.444667 frames)
AmlVideoSink: Adjust PTS - pts=0.914956 vpts=0.033333 drift=-0.881622 (-26.448667 frames)
AmlVideoSink: Adjust PTS - pts=0.915122 vpts=0.033333 drift=-0.881789 (-26.453667 frames)
```

```
brian@brian-desktop:/media/hdd$ mediainfo Toy\ Story\ 3\ -\ Trailer\ 3\ 6450_D1.mp4 
General
Complete name                            : Toy Story 3 - Trailer 3 6450_D1.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (mp41)
File size                                : 63.8 MiB
Duration                                 : 2mn 29s
Overall bit rate mode                    : Variable
Overall bit rate                         : 3 572 Kbps
Encoded date                             : UTC 1970-01-01 00:00:00
Tagged date                              : UTC 1970-01-01 00:00:00
Writing application                      : PotEncoder

Video
ID                                       : 1
Format                                   : MPEG-4 Visual
Format profile                           : Simple@L1
Format settings, BVOP                    : No
Format settings, QPel                    : No
Format settings, GMC                     : No warppoints
Format settings, Matrix                  : Default (H.263)
Codec ID                                 : 20
Duration                                 : 2mn 29s
Bit rate                                 : 3 469 Kbps
Width                                    : 800 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 5:3
Frame rate mode                          : Constant
Frame rate                               : 30.000 fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Compression mode                         : Lossy
Bits/(Pixel*Frame)                       : 0.301
Stream size                              : 62.0 MiB (97%)
Writing library                          : Lavc52.108.0
Encoded date                             : UTC 1970-01-01 00:00:00
Tagged date                              : UTC 1970-01-01 00:00:00

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : 40
Duration                                 : 2mn 29s
Bit rate mode                            : Variable
Bit rate                                 : 96.0 Kbps
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 44.1 KHz
Frame rate                               : 43.066 fps (1024 spf)
Compression mode                         : Lossy
Stream size                              : 1.74 MiB (3%)
Encoded date                             : UTC 1970-01-01 00:00:00
Tagged date                              : UTC 1970-01-01 00:00:00
```
This media file's available download link is [here.](https://mega.nz/#!34cyzCRR!tbXhEwMSRoLLTuuspJPqCsI_cGaJUIYpnoLJAEoTR0Y)

**Comment by OtherCrashOverride** [comment] 2016-12-21 03:13
I can reproduce this issue and am working on a fix.

**Comment by OtherCrashOverride** [comment] 2016-12-21 04:22
The issue originates from this being an unusual bitstream.  It is MPEG4 (like DivX) but has H264 start codes.  However, since it is not AnnexB compliant, I added a code path to work around the issue.

In the branch "next", the following commit works around this issue:
https://github.com/OtherCrashOverride/c2play/commit/ea965bd94ab02673a3fe8e3bc7b3a7cd8d2c33d4

[Edit]
Note that for the sample provided, there are audible gaps in the sound stream.  These are also present on Kodi and VLC (x86) and do not indicate a problem with c2play.

[Edit2]
The hang happens as a result of bad data being sent to the codec kernel driver.  Preventing the hang would require additional validation in the kernel driver by Amlogic.

**Comment by bkrepo** [comment] 2016-12-21 04:49
This media file works on next branch. :+1: 
About haining in the kernel side, could you suggest simple sample code in order to reproduce the hang? 
We will look into the problem after the codec driver hang issue is uploaded to the odroid forum or HK's linux repository.

**Comment by OtherCrashOverride** [comment] 2016-12-21 04:59
> could you suggest simple sample code in order to reproduce the hang?

My only suggestion would be to use the v1.0.0 version of c2play with the sample media you provided.  The hang is likely dependent on codec firmware micro-code as well.  The data to hang it will likely differ for MPEG4, H264, and HEVC.

For this particular issue, the data being sent to the codec was raw data contained in the video packet:
https://github.com/OtherCrashOverride/c2play/blob/master/src/Media/AmlVideoSink.cpp#L351

This difference now is that the "extra data" is parsed as H264 and sent before that same data that hung decoder is sent.
https://github.com/OtherCrashOverride/c2play/blob/ea965bd94ab02673a3fe8e3bc7b3a7cd8d2c33d4/src/Media/AmlVideoSink.cpp#L269-L272

**Comment by bkrepo** [comment] 2016-12-21 06:52
Okay, thank you @OtherCrashOverride.

**Comment by OtherCrashOverride** [comment] 2017-01-07 20:24
This should now be fully resolved in the 'next' branch.  Please feel to open another issue if you experience any further issues.

**Closed as completed by OtherCrashOverride** 2017-01-07 20:24 UTC
Labels: bug
